version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'

  postgres:
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db-name
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_CONF_SERVER_MODE: 'False'
    ports:
      - '5050:80'